### ISSUE TITLE
[BUG] Launch.sh has wrong file path after installing

### ISSUE THREAD

**Issue by Muffinmaker2** [AugustusClient/AugustusLinux#12]
**Describe the bug**

After installing, the Launcher.sh has the wrong file path to the wine folder.

The script wants to go into the folder with "wine" in the front, but there is only a folder without that. 

Removing the wine in the script or adding it to the folder fixes it. Idk atm how to fix it but that would need fixing

**To Reproduce**
1. Run install script
2. Let if finish
3. Profit?

**Expected behavior**
Idk what it supposed to do but i guess work properly?

**Screenshots**
![image](https://github.com/user-attachments/assets/434ac788-07b2-442e-a581-3edbfc179c7b)

**Distro**
![image](https://github.com/user-attachments/assets/b302628d-bdcc-4c8a-8efa-377ce03e8116)

**Comment by PixGuy** [comment]
The issue comes from a recent change in the naming convention of wine-ge's latest release. In the recent release, the _wine-_ prefix has been removed from the folder name, while it's still present in the .tar.xz file. Since the folder's location is retrieved from the .tar.xz file, it's causing a mismatch. This has been fixed, apologies for any inconvenience it might've caused.
